# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "serverledge"
    static_configs:
      - targets: ["192.168.178.148:1323", "192.168.178.148:1340", "192.168.178.148:1329", "192.168.178.148:1310", "192.168.178.148:1327","192.168.178.148:1328"]


